---
- name: Install Dockge container on Docker hosts
  hosts: docker

  tasks:
    - name: Deploy Dockge container (prod-control)
      community.docker.docker_container:
        name: dockge
        image: louislam/dockge:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "/mnt/docker/appdata/prod-control/dockge:/app/data"
          - "/mnt/docker/stacks/prod-control:/mnt/docker/stacks/prod-control"
        env:
          DOCKGE_STACKS_DIR: "/mnt/docker/stacks/prod-control"
      when: inventory_hostname == 'prod-control'

    - name: Deploy Dockge container (all other hosts)
      community.docker.docker_container:
        name: dockge
        image: louislam/dockge:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "/mnt/docker/appdata/dockge:/app/data"
          - "/mnt/docker/stacks:/mnt/docker/stacks"
        env:
          DOCKGE_STACKS_DIR: "/mnt/docker/stacks"
      when: inventory_hostname != 'prod-control'
