[homelab_dmz]
dmz-authentik-server                      ansible_host=dmz-authentik-server
dmz-caddy-server                          ansible_host=dmz-caddy-server
dmz-calibre-server                        ansible_host=dmz-calibre-server
dmz-freshrss-server                       ansible_host=dmz-freshrss-server
dmz-immich-server                         ansible_host=dmz-immich-server
dmz-vaultwarden-server                    ansible_host=dmz-vaultwarden-server

[homelab_dmz:vars]
ansible_user=msviridov


[homelab_prod]
jellyfin-server                           ansible_host=jellyfin-server
prod-control-server                       ansible_host=prod-control-server
prod-caddy-server                         ansible_host=prod-caddy-server
prod-docker-server                        ansible_host=prod-docker-server
prod-influxdb-server                      ansible_host=prod-influxdb-server
prod-pms-server                           ansible_host=prod-pms-server
file-server                               ansible_host=file-server
docker-server                             ansible_host=docker-server

[homelab_prod:vars]
ansible_user=msviridov


[homelab_mgmt]
heimdall                                  ansible_host=heimdall
pbs-server                                ansible_host=pbs-server

[homelab_mgmt:vars]
ansible_user=root


[club]
pve-club ansible_host=pve-club

[club:vars]
ansible_user=root

[all:vars]
ansible_python_interpreter=auto_silent
